# 1
## Q1
 ```{r}
library(tidyverse)
library(Stat2Data)
library(dplyr)
data("Hawks")
filter(Hawks, Species == 'RT' & Weight >= 1000)
hSF <- select(Hawks, Wing, Weight, Tail )
head(hSF)

head(select(filter(Hawks, Species == 'RT' & Weight >= 1000),Wing, Weight, Tail))

head(hSF <- Hawks %>%
  filter(Species == 'RT' & Weight >= 1000) %>%
  select(Wing, Weight, Tail ))
head(hSF)
```
## Q2
 ```{r}
 num_variables <- ncol(hSF)
 print(num_variables)
 print(nrow(hSF))
 ```
 
#1.2
##Q1
 ```{r}
head(hSF %>% arrange(Wing))
 ```
#1.3, 1.4
##Q1,Q2,Q3
 ```{r}
code <- c("CH","RT","SS")
full <- c("Cooper's", "Red-tailed", "Sharp-shinned")
hawkSpeciesNameCodes <- data.frame(species_code = code, species_name_full = full)
print(hawkSpeciesNameCodes)

hawkSpeciesNameCodes %>% rename(Species = species_code)
hawksFullName <- Hawks %>% rename(species_code = Species)
head(hawksFullName)
hawksFullName_res <- select(left_join(hawksFullName, hawkSpeciesNameCodes), -species_code)
head(hawksFullName_res)

head(select(hawksFullName_res, Wing, Weight, Tail ),7)

hawksWithBMI <- hawksFullName_res %>% rename(Species = species_name_full)
head(hawksFullName_res)
head(hawksWithBMI %>%
    mutate( bird_BMI = 1000 * (Weight / (Wing^2))) %>%
    arrange(desc(bird_BMI)) %>%
    select(bird_BMI,  Species ))

 ```
# 1.5
## Q1,Q2,Q3
```{r}
 hawksWithBMI %>% 
  group_by(Species) %>%
   summarize(num_rows=n(), mn_wing=mean(Wing),nd_wing= median(Wing,, na.rm=TRUE),t_mn_wing=mean(Wing,0.1), b_wt_ratio=max(Wing/Tail,na.rm=TRUE))

Num_NAs <- hawksWithBMI %>% group_by(Species) %>% select(Wing, Weight, Culmen, Hallux, Tail, StandardTail,Tarsus, Crop) %>% summarize(across(everything(), ~sum(is.na(.x))))
print(Num_NAs)

 ``` 

## 2
```{r}
library(tidyverse)

impute_by_median<-function(x){
  mu<-median(x,na.rm=1) # first compute the mean of x
  impute_f<-function(z){ # coordinate-wise imputation
    if(is.na(z)){
      return(mu) # if z is na replace with mean
    }else{
      return(z) # otherwise leave in place
    } }
return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}
v<-c(1,2,NA,4)
impute_by_median(v)

x <- seq(0, 10, by = 0.1)
y <- 5 * x + 1
df_xy <- data.frame(x = x, y = y)
head(df_xy)

df_xy %>%
mutate(z=map2_dbl(x,y,~.x+.y)) %>%
head(5)

sometimes_missing <- function(index, value) {
  if (index %% 5 == 0) {
    return(NA)
  } else {
    return(value)
  }
}

sometimes_missing(14,25)
sometimes_missing(15,25)

df_xy_missing <- df_xy %>%
  mutate(row_num = row_number()) %>%
  mutate(y = map2_dbl(row_num, y, sometimes_missing)) %>%
  select(-row_num)

print(head(df_xy_missing, 10))
    
df_xy_imputed <- df_xy_missing %>%
  mutate(y = impute_by_median(y))
head(df_xy_imputed)


 ```
## 2.2
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 